name: Master
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Pause for 25 seconds
        run: |
          echo done
          sleep 25